name: Hasura Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Run Hasura workflow
        run: |
          # hasura migrate create init --from-server --endpoint ${{ secrets.HASURA_ENDPOINT }} --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }}
          hasura migrate apply --endpoint ${{ secrets.HASURA_ENDPOINT }} --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }} --skip-execution --database-name ${{ secrets.HASURA_DATABASE }}
          hasura metadata export --endpoint ${{ secrets.HASURA_STG_ENDPOINT }} --admin-secret ${{ secrets.HASURA_STG_ADMIN_SECRET }}
